### ISSUE TITLE
Add view counts to comparison pages

### ISSUE THREAD

**Issue by Daiz** [Fugiman/diff.pics#6]
Much like screenshotcomparison does:

![image](https://cloud.githubusercontent.com/assets/3596343/23828619/90f161b0-06e0-11e7-8b95-72fe9a1e8593.png)

**Comment by Fugiman** [comment]
Is this actually useful for anything or just idle curiosity?

**Comment by Daiz** [comment]
The latter, really

It would just be nice-to-know information

**Comment by Fugiman** [comment]
Done
