### ISSUE TITLE
SSL/TLS invalid cert

### ISSUE THREAD

**Issue by FichteFoll** [Fugiman/diff.pics#7]
The server currently hands a cert that is only valid for the domain names:
```
DNS Name: brainpower.rip
DNS Name: www.brainpower.rip
```

A redirect from http to https pages would be nice, too.

**Comment by wopian** [comment]
Currently https://diff.pics redirects you to brainpower.rip too - which is a *slight* issue when using HTTPS everywhere.

**Comment by Fugiman** [comment]
This should be fixed now

**Comment by wopian** [comment]
@Fugiman the redirect's fixed, but all the assets are loaded via HTTP and blocked 😢 

![](http://i.imgur.com/9w4nSv6.png)
